myproject/myproject/apps/plants/urls.py
from django.urls import path

from . import views

app_name = 'plants'
urlpatterns = [

    # --------- USER VIEWS ---------
    # Plants list
    path('', views.list, name = 'list'),

    # Plant detail
    path('<int:plant_id>/', views.plant_detail, name = 'plant_detail'),

    # --------- ADMIN VIEWS ---------
    # Plants list
    path('admin', views.admin_list, name = 'admin_list'),

    # Pages
    path('admin/<int:plant_id>/', views.admin_plant_detail, name = 'admin_plant_detail'),
    path('admin/add-plant-page/', views.admin_add_plant_page, name = 'admin_add_plant_page'),

    # Actions
    path('admin/<int:plant_id>/save-data-action/', views.admin_save_plant_data, name = 'admin_save_plant_data'),
    path('admin/add-plant-action/', views.admin_add_plant_action, name = 'admin_add_plant_action'),
    path('admin/<int:plant_id>/delete-plant-action/', views.admin_delete_plant_action, name = 'admin_delete_plant_action')
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('plants/', include('plants.urls')),
    path('admin/', admin.site.urls),
]

myproject/myproject/apps/plants/models.py
from django.db import models


class PlantType(models.Model):
    plant_type_name = models.CharField("Наименование типа растения", max_length = 100)


class WindowType(models.Model):
    window_type_name = models.CharField("Наименование типа окна для растнения", max_length = 100)


class Plant(models.Model):
    plant_name = models.CharField('Наименование растения', max_length = 255)
    plant_requirements = models.TextField('Требование по уходу')

    # Foreign Keys
    plant_type = models.ForeignKey(PlantType, on_delete = models.CASCADE)
    plant_window_type = models.ForeignKey(WindowType, on_delete = models.CASCADE)

myproject/myproject/apps/plants/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from .models import Plant, PlantType, WindowType


# ------- USER VIEWS -------

def list(request):
    plants_list = Plant.objects.all()
    return render(request, 'plants/user/list.html', {'plants_list': plants_list})


def plant_detail(request, plant_id):
    try:
        plant_info = Plant.objects.get(id = plant_id)
    except:
        raise Http404("Статья не найдена!")

    return render(request, 'plants/user/plant_detail.html', {'plant_info': plant_info})


# ------- ADMIN VIEWS -------

def admin_list(request):
    plants_list = Plant.objects.all()
    return render(request, 'plants/admin/list.html', {'plants_list': plants_list})


def admin_plant_detail(request, plant_id):
    try:
        plant_info = Plant.objects.get(id = plant_id)
    except:
        raise Http404("Статья не найдена!")

    # Data
    all_plant_types = PlantType.objects.all()
    all_window_types = WindowType.objects.all()

    return render(request, 'plants/admin/plant_detail.html', {'plant_info': plant_info,
                                                              'all_plant_types': all_plant_types,
                                                              'all_window_types': all_window_types})


def admin_save_plant_data(request, plant_id):
    try:
        plant_info = Plant.objects.get(id = plant_id)
    except:
        raise Http404("Статья не найдена!")

    # Set new data
    plant_info.plant_name = request.POST['plant_name']
    plant_info.plant_requirements = request.POST['plant_requirements']
    plant_info.plant_type = PlantType.objects.get(id = int(request.POST['plant_type']))
    plant_info.plant_window_type = WindowType.objects.get(id = int(request.POST['plant_window_type']))

    # Save new data
    plant_info.save()

    return HttpResponseRedirect(reverse('plants:admin_plant_detail', args = (plant_id,)))


def admin_add_plant_page(request):
    # Data
    all_plant_types = PlantType.objects.all()
    all_window_types = WindowType.objects.all()

    return render(request, 'plants/admin/add_plant.html', {'all_plant_types': all_plant_types,
                                                           'all_window_types': all_window_types})


def admin_add_plant_action(request):
    plant_info = Plant()

    # Set new data
    plant_info.plant_name = request.POST['plant_name']
    plant_info.plant_requirements = request.POST['plant_requirements']
    plant_info.plant_type = PlantType.objects.get(id = int(request.POST['plant_type']))
    plant_info.plant_window_type = WindowType.objects.get(id = int(request.POST['plant_window_type']))

    # Save new data
    plant_info.save()

    return HttpResponseRedirect(reverse('plants:admin_list'))


def admin_delete_plant_action(request, plant_id):
    try:
        plant = Plant.objects.get(id = plant_id)
    except:
        raise Http404("Статья не найдена!")

    plant.delete()

    return HttpResponseRedirect(reverse('plants:admin_list'))

myproject/myproject/templates/admin_template.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% block title %} Мой сайт {% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'plants:admin_list' %}">Список всех растений</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Сделать заказ</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'plants:admin_add_plant_page' %}">Добавить растение</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'plants:list' %}">Вид пользователя</a>
            </li>
        </ul>
    </div>

    <!-- If user is logged in-->
    <div class="user-authorized">
        <div class="user-name">
            Рады вам: "Alex"
        </div>
        <div class="order-button">
            <a class="order-button__link" href="#">
                <img class="order-button__image" src="{% static 'images/basket.png' %}" alt="">
            </a>
        </div>
        <div class="navbar-button logout-button">
            <a href="#">Выход</a>
        </div>
    </div>

    <!-- If the user is not logged in -->
    <div class="navbar-button login-button hide">
        <a href="authorization.html">Войти</a>
    </div>
</nav>

{% block content %} {% endblock %}

<script src="{% static 'js/main.js' %}"></script>
</body>
</html>

myproject/myproject/templates/plants/admin/add_plant.html
{% extends 'admin_template.html' %}
{% load static %}

{% block title %} Добавить новое растение {% endblock %}

{% block content %}
<div class="container edit-plant-container">
    <div class="col-6 align-content-center">
        <div class="media">
            <div class="row justify-content-md-center plant-info">
                <img class="plant-info__img align-self-start" src="{% static 'images/1.png' %}" alt="...">
                <form method="POST" action="{% url 'plants:admin_add_plant_action' %}" class="plant-edit-form">

                    {% csrf_token %}

                    <div class="form-group">
                        <label for="plantNameField">Наименование</label>
                        <input name="plant_name" type="text" class="form-control" id="plantNameField"
                               value="">
                    </div>
                    <div class="form-group">
                        <label for="plantTypeField">Тип растения</label>
                        <select class="form-control" id="plantTypeField" name="plant_type">
                            {% for plant_type in all_plant_types %}
                            <option value="{{plant_type.id}}">{{plant_type.plant_type_name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="plantWindowField">Подходящее окно для освещения</label>
                        <select class="form-control" id="plantWindowField" name="plant_window_type">
                            {% for window_type in all_window_types %}
                            <option value="{{window_type.id}}">{{window_type.window_type_name}}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="plantRequirementsField">Описание и требования по уходу</label>
                        <textarea class="form-control" id="plantRequirementsField" rows="3" name="plant_requirements">
                            {{plant_info.plant_requirements}}</textarea>
                    </div>

                    <div class="form-group edit-plant-container__button-block">
                        <button type="submit" class="btn btn-primary">Добавить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

myproject/myproject/templates/plants/admin/list.html
{% extends 'admin_template.html' %}
{% load static %}

{% block title %} Комнатные растения {% endblock %}

{% block content %}
<div class="container">
    <div class="plants-list col-12 align-content-center">
        <h1 class="text-center">Список всех растений</h1>
        {% if plants_list %}

        {% for plant in plants_list %}
        <div class="list-item">
            <a class="media plants-list__item" href="{% url 'plants:admin_plant_detail' plant.id %}">
                <div class="row justify-content-md-center">
                    <div class="plants-list__img">
                        <img src="{% static 'images/1.png' %}" class="align-self-start mr-3" alt="...">
                    </div>
                    <div class="media-body">
                        <h5 class="mt-0">{{plant.plant_name}}</h5>
                        <p>{{plant.plant_requirements}}</p>
                    </div>
                </div>
            </a>
            <div class="list-item__buttons">
                <div class="list-item__button">
                    <a href="{% url 'plants:admin_delete_plant_action' plant.id %}" class="btn-danger">Удалить</a>
                </div>
                <div class="list-item__button">
                    <a href="{% url 'plants:admin_plant_detail' plant.id %}" class="btn-success">Изменить</a>
                </div>
            </div>
        </div>
        {% endfor %}

    </div>
</div>

{% else %}
Растения не найдены!
{% endif %}
{% endblock %}

myproject/myproject/templates/plants/admin/plant_detail.html
{% extends 'admin_template.html' %}
{% load static %}

{% block title %} {{ plant_info.plant_name }} {% endblock %}

{% block content %}
<div class="container edit-plant-container">
    <div class="col-6 align-content-center">
        <div class="media">
            <div class="row justify-content-md-center plant-info">
                <img class="plant-info__img align-self-start" src="{% static plant_image_path %}" alt="...">
                <form class="plant-edit-form">
                    <label for="plantImage">Загрузить картинку: </label>
                    <input type="file" name="plantImage" id="plantImage">
                    <div class="form-group">
                        <label for="plantNameField">Наименование растения</label>
                        <input type="text" class="form-control" id="plantNameField">
                    </div>
                    <div class="form-group">
                        <label for="plantTypeField">Тип растения</label>
                        <select class="form-control" id="plantTypeField">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="plantWindowField">Подходящее окно для освещения</label>
                        <select class="form-control" id="plantWindowField">
                            <option>1</option>
                            <option>2</option>
                            <option>3</option>
                            <option>4</option>
                            <option>5</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="plantRequirementsField">Описание и требования по уходу</label>
                        <textarea class="form-control" id="plantRequirementsField" rows="3"></textarea>
                    </div>

                    <div class="form-group edit-plant-container__button-block">
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

myproject/myproject/templates/plants/user/list.html
{% extends 'user_template.html' %}
{% load static %}

{% block title %} Комнатные растения {% endblock %}

{% block content %}
<div class="container">
    <div class="plants-list col-12 align-content-center">
        <h1 class="text-center">Список всех растений</h1>
        {% if plants_list %}

        {% for plant in plants_list %}
        <a class="media plants-list__item list-item" href="{% url 'plants:plant_detail' plant.id %}">
            <div class="row justify-content-md-center">
                <div class="plants-list__img">
                    <img src="{% static 'images/1.png' %}" class="align-self-start mr-3" alt="...">
                </div>
                <div class="media-body">
                    <h5 class="mt-0">{{plant.plant_name}}</h5>
                    <p>{{plant.plant_requirements}}</p>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>


{% else %}
Растения не найдены!
{% endif %}
{% endblock %}

myproject/myproject/templates/plants/user/plant_detail.html
{% extends 'user_template.html' %}
{% load static %}

{% block title %} {{ plant_info.plant_name }} {% endblock %}

{% block content %}
<div class="container">
  <div class="col-12 align-content-center">
    <div class="media">
      <div class="row justify-content-md-center plant-info">
        <img class="plant-info__img align-self-center" src="{% static 'images/1.png' %}" class="align-self-start mr-3" alt="...">
        <h4 class="mt-0 align-self-center">{{ plant_info.plant_name }}</h4>
        <div class="media-body plant-info__text">
          <div class="plant-info__requirements">
            <h3 class="mt-0">Описание и требования по уходу</h3>
            <span>{{ plant_info.plant_requirements }}</span>
          </div>
          <div class="plant-info__type">
            <span class="plant-info__subtitle">Тип растения: </span>{{plant_info.plant_type.plant_type_name}}
          </div>
          <div class="plant-info__window-type">
            <span class="plant-info__subtitle">Подходящее окно: </span> {{plant_info.plant_window_type.window_type_name}}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

myproject/myproject/templates/user_template.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% block title %} Мой сайт {% endblock %}</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'plants:list' %}">Список всех растений</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="#">Сделать заказ</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'plants:admin_list' %}">Вид админа</a>
            </li>
        </ul>
    </div>

    <!-- If user is logged in-->
    <div class="user-authorized">
        <div class="user-name">
            Рады вам: "Alex"
        </div>
        <div class="order-button">
            <a class="order-button__link" href="#">
                <img class="order-button__image" src="{% static 'images/basket.png' %}" alt="">
            </a>
        </div>
        <div class="navbar-button logout-button">
            <a href="#">Выход</a>
        </div>
    </div>

    <!-- If the user is not logged in -->
    <div class="navbar-button login-button hide">
        <a href="authorization.html">Войти</a>
    </div>
</nav>

{% block content %} {% endblock %}

<script src="{% static 'js/main.js' %}"></script>
</body>
</html>